services:
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # NocturnalOps Api
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # nocturnal-api:
  #   container_name: nocturnal-api
  #   build:
  #     context: ../../
  #     dockerfile: nocturnal-api/Dockerfile
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - nocturnal-net

  # #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # # NocturnalOps Frontend
  # #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # nocturnal-app:
  #   container_name: nocturnal-app
  #   build:
  #     context: ../../frontend/nocturnal-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   # environment:
  #   #   - port=3000
  #   # env_file:
  #   #   - ../docker.env
  #   # depends_on:
  #   #   reverse-proxy:
  #   #     condition: service_healthy
  #   #   laniakea-mongodb:
  #   #     condition: service_healthy  

  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # Cloud Stacks
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  # Google Cloud - Datastore
  nocturnal-gcp-datastore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:392.0.0
    # environment:
    #   - DATASTORE_DATASET=my-project-id
    #   - DATASTORE_EMULATOR_HOST=[::1]:8630
    #   - DATASTORE_EMULATOR_HOST_PATH=[::1]:8630/datastore
    #   - DATASTORE_HOST=http://[::1]:8630
    #   - DATASTORE_PROJECT_ID=my-project-id
    #   - DATASTORE_USE_PROJECT_ID_AS_APP_ID=true
    ports:
      - "8000:8081"
    command: gcloud beta emulators datastore start --project=datastore-wrapper --host-port=0.0.0.0:8081 --project emulator --store-on-disk
    # --no-store-on-disk --use-firestore-in-datastore-mode
    # networks:
    #   - nocturnal-net

# networks:
#   nocturnal-net:
#     external: true